name: Supreme
author: RelativoBR, Especttra, WilianSantosBR e Mynothauro, cworldstar
description: Supreme is an addon for Slimefun which adds 100+ various new resources that will allow you to craft powerful new items, weapons, tools and armor. These can be made up from titanium, aurum, adamantium, thornium with some being magical, rare, epic, legendary or supreme! It also adds 12 new electric generators, 5 new capacitors and even more...
main: com.github.relativobr.supreme.Supreme
website: https://github.com/Sniperkaos/Supreme1.21.8
depend: [Slimefun]
softdepend: [InfinityExpansion2, ProtocolLib]
version: ${project.version}
api-version: 1.17
